'''Token constants.

This implementation isn't very DRY, but it's simple and works with code completionin IDE. This is also the method that the stdlib uses in token.py'''

IDENTIFIER = 'IDENTIFIER'
STRING = 'STRING'
NUMBER = 'NUMBER'
COLON = 'COLON'
SEMICOLON = 'SEMICOLON'
COMMA = 'COMMA'
PLUS = 'PLUS'
MINUS = 'MINUS'
MULTIPLY = 'MULTIPLY'
DIVIDE = 'DIVIDE'
OPENPAREN = 'OPENPAREN'
CLOSEPAREN = 'CLOSEPAREN'
LT = 'LT'
LTE = 'LTE'
GT = 'GT'
GTE = 'GTE'
NOTEQUAL = 'NOTEQUAL'
EQUAL = 'EQUAL'
ASSIGN = 'ASSIGN'
OPENBRACE = 'OPENBRACE'
CLOSEBRACE = 'CLOSEBRACE'
EOF = 'EOF'