'''Token constants.

This implementation isn't very DRY, but it's simple and works with code
completion. This is also similar to the method that the stdlib uses in
token.py.

The token types are assigned strings for readibility instead of the classic
arbitrary integer values. This is not a performance issue, because python
interns small strings, which allows equality comparisons to just use a pointer
compare, which is the same speed as an integer compare. '''

IDENTIFIER = 'IDENTIFIER'
STRING = 'STRING'
NUMBER = 'NUMBER'
SEMICOLON = 'SEMICOLON'
COMMA = 'COMMA'
PLUS = 'PLUS'
MINUS = 'MINUS'
MULTIPLY = 'MULTIPLY'
DIVIDE = 'DIVIDE'
OPENPAREN = 'OPENPAREN'
CLOSEPAREN = 'CLOSEPAREN'
LT = 'LT'
LTE = 'LTE'
GT = 'GT'
GTE = 'GTE'
NOTEQUAL = 'NOTEQUAL'
EQUAL = 'EQUAL'
ASSIGN = 'ASSIGN'
OPENBRACKET = 'OPENBRACKET'
CLOSEBRACKET = 'CLOSEBRACKET'
STRING_TYPE = 'STRING_TYPE'
INT = 'INT'
BOOL = 'BOOL'
FLOAT = 'FLOAT'
GLOBAL = 'GLOBAL'
IN = 'IN'
OUT = 'OUT'
IF = 'IF'
THEN = 'THEN'
ELSE = 'ELSE'
FOR = 'FOR'
AND = 'AND'
OR = 'OR'
NOT = 'NOT'
PROGRAM = 'PROGRAM'
PROCEDURE = 'PROCEDURE'
BEGIN = 'BEGIN'
RETURN = 'RETURN'
END = 'END'
TRUE = 'TRUE'
FALSE = 'FALSE'
ERROR = 'ERROR'
IS = 'IS'
EOF = 'EOF'